[package]
name = "caesar-cli"
version = "0.4.1"
authors = ["lost <derribado@tutanota.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rayon = "1.3.0"
num_cpus = "1.10.1"
caesar = { git = "https://git.cryptid.cc/lost/caesar-rs" }
thiserror = "1.0.10"

[profile.release]
lto = "on"
