[package]
name = "csr-cli"
version = "0.5.0"
authors = ["lost <derribado@tutanota.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rayon = "1.3.0"
num_cpus = "1.10.1"
csr = "0.8"
thiserror = "1.0.10"

[profile.release]
lto = "on"

[[bin]]
name = "csr"
path = "src/main.rs"
