[package]
name = "caesar-cli"
version = "0.1.0"
authors = ["lost <derribado@tutanota.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.10.1"
caesar = { git = "https://git.cryptid.cc/lost/caesar-rs" }
