[package]
name = "caesar-cli"
version = "0.3.1"
authors = ["lost <derribado@tutanota.com>"]
edition = "2018"

[dependencies]
rayon = "1.3.0"
num_cpus = "1.10.1"
caesar = { git = "https://git.cryptid.cc/lost/caesar-rs" }

[profile.release]
lto = "on"
